repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff
        args: [--fix]
        files: ^selvage/src/
      - id: ruff-format
        files: ^selvage/src/
